curl http://localhost:3000 -H "Token:test-token"
echo ""
curl http://localhost:3000 -H "Token:test-token"
echo ""
curl http://localhost:3000 -H "Token:test-token"
echo ""
curl http://localhost:3000 -H "Token:test-token"
echo ""
curl http://localhost:3000 -H "Token:test-token"
echo ""
curl -i http://localhost:3000 -H "Token:test-token"
echo ""
